### ISSUE TITLE
"npm run dev" failed

### ISSUE THREAD

**Issue by izzizz** [bdefore/universal-redux-jwt#1] opened 2016-01-24 15:33 UTC
error message: 

```
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/ripple/style.scss
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/button/style.scss
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/input/style.scss
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/overlay/style.scss
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/snackbar/style.scss
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/card/style.scss
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/avatar/style.scss
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/commons.scss
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/flexboxgrid/dist/flexboxgrid.css
```

please help, thanks.

**Comment by bdefore** [comment] 2016-01-24 17:06
These errors are benign, and will log out the first time you start up universal-redux. @halt-hammerzeit does your webpack-isomorphic-tools new verbose flag hide these when false?

That said, there is an issue due to the react toolbox logic causing the server to fail to serve content on the first load. https://github.com/bdefore/universal-redux/issues/32 If you exit and re-run `npm run dev` it should work.

**Comment by catamphetamine** [comment] 2016-01-24 17:08
@bdefore no, `verbose` just reduces webpack build info output.

these are not info, these are errors and must be dealt with.

In this case, seems like these entries are absent from `webpack-assets.json`.
the OP should post this file and then we'll see.

**Comment by izzizz** [comment] 2016-01-25 05:43
this is the webpack-assets.json in node_modules/universal-redux/:
[webpack-assets.json.zip](https://github.com/bdefore/universal-redux-jwt/files/102798/webpack-assets.json.zip)

**Comment by izzizz** [comment] 2016-01-25 06:23
Just removed node_modules, run npm install again, the error is gone... guess it's my local env problem.

**Comment by dbhandel** [comment] 2016-01-29 18:39
npm run dev fails for me too. I have the redis server running and used nvm to change to 5.2.0
Any help would be appreciated. Here's the terminal output:

npm run dev

> universal-redux-jwt@0.0.1 dev /Users/davidhandel/Desktop/universal-redux-jwt-master
> concurrent --kill-others "npm run watch-client" "npm run api-server" "npm run auth-server" "npm run dev-server"

[0]
[0] > universal-redux-jwt@0.0.1 watch-client /Users/davidhandel/Desktop/universal-redux-jwt-master
[0] > better-npm-run watch-client
[0]
[1]
[1] > universal-redux-jwt@0.0.1 api-server /Users/davidhandel/Desktop/universal-redux-jwt-master
[1] > better-npm-run api-server
[1]
[2]
[2] > universal-redux-jwt@0.0.1 auth-server /Users/davidhandel/Desktop/universal-redux-jwt-master
[2] > better-npm-run auth-server
[2]
[3]
[3] > universal-redux-jwt@0.0.1 dev-server /Users/davidhandel/Desktop/universal-redux-jwt-master
[3] > better-npm-run dev-server
[3]
[0] running better-npm-run in /Users/davidhandel/Desktop/universal-redux-jwt-master
[1] running better-npm-run in /Users/davidhandel/Desktop/universal-redux-jwt-master
[2] running better-npm-run in /Users/davidhandel/Desktop/universal-redux-jwt-master
[0] Executing script: watch-client
[0]
[0] to be executed: universal-redux-watch
[1] Executing script: api-server
[1]
[1] to be executed: node ./bin/start_api
[2] Executing script: auth-server
[2]
[2] to be executed: node ./bin/start_auth
[3] running better-npm-run in /Users/davidhandel/Desktop/universal-redux-jwt-master
[3] Executing script: dev-server
[3]
[3] to be executed: node ./bin/start
[2] ==> 💻  Authentication server running at undefined:undefined
[1] ==> 💻  API server running at http://localhost:3000/v1
[0] Loaded project level config { server: { host: 'localhost', port: 3000 },
[0]   globals:
[0]    { **LOGGER**: true,
[0]      **DEVTOOLS**: true,
[0]      **DEVTOOLS_IS_VISIBLE**: true,
[0]      **API_ENDPOINT**: '/api' },
[0]   lint:
[0]    { enabled: false,
[0]      config: '/Users/davidhandel/Desktop/universal-redux-jwt-master/.eslintrc' },
[0]   notifications: true,
[0]   verbose: true,
[0]   routes: '/Users/davidhandel/Desktop/universal-redux-jwt-master/src/routes.js',
[0]   redux:
[0]    { reducers: '/Users/davidhandel/Desktop/universal-redux-jwt-master/src/redux/modules/index.js',
[0]      middleware: '/Users/davidhandel/Desktop/universal-redux-jwt-master/src/redux/middleware/index.js' },
[0]   html: { head: '/Users/davidhandel/Desktop/universal-redux-jwt-master/src/containers/Head/Head.js' },
[0]   webpack: { config: { resolve: [Object] } } }
[0]
[0] Babel config:
[0] { presets: [ 'es2015', 'stage-0', 'react' ],
[0]   plugins:
[0]    [ [ 'transform-runtime' ],
[0]      [ 'typecheck' ],
[0]      [ 'transform-decorators-legacy' ] ],
[0]   env:
[0]    { development:
[0]       { plugins:
[0]          [ [ 'react-transform',
[0]              { transforms:
[0]                 [ { transform: 'react-transform-hmr',
[0]                     imports: [ 'react' ],
[0]                     locals: [ 'module' ] },
[0]                   { transform: 'react-transform-catch-errors',
[0]                     imports: [ 'react', 'redbox-react' ] } ] } ] ] },
[0]      production: { plugins: [] } },
[0]   cacheDirectory: true }
[0]
[0] Webpack config:
[0] { context: '/Users/davidhandel/Desktop/universal-redux-jwt-master',
[0]   output:
[0]    { path: '/Users/davidhandel/Desktop/universal-redux-jwt-master/static/dist',
[0]      filename: '[name]-[hash].js',
[0]      chunkFilename: '[name]-[chunkhash].js',
[0]      publicPath: 'http://localhost:3001/dist/' },
[0]   progress: true,
[0]   stats: {},
[0]   failOnError: true,
[0]   entry:
[0]    { main:
[0]       [ '/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/lib/client.js',
[0]         'webpack-hot-middleware/client?path=http://localhost:3001/**webpack_hmr' ] },
[0]   module:
[0]    { loaders:
[0]       [ { test: /.jsx?$/,
[0]           exclude: /node_modules/,
[0]           loaders: [ 'babel-loader?{"presets":["es2015","stage-0","react"],"plugins":[["transform-runtime"],["typecheck"],["transform-decorators-legacy"]],"env":{"development":{"plugins":[["react-transform",{"transforms":[{"transform":"react-transform-hmr","imports":["react"],"locals":["module"]},{"transform":"react-transform-catch-errors","imports":["react","redbox-react"]}]}]]},"production":{"plugins":[]}},"cacheDirectory":true}' ] },
[0]         { test: /.json$/, loader: 'json-loader' },
[0]         { test: /.woff(\?v=\d+.\d+.\d+)?$/,
[0]           loader: 'url?limit=10000&mimetype=application/font-woff' },
[0]         { test: /.woff2(\?v=\d+.\d+.\d+)?$/,
[0]           loader: 'url?limit=10000&mimetype=application/font-woff' },
[0]         { test: /.ttf(\?v=\d+.\d+.\d+)?$/,
[0]           loader: 'url?limit=10000&mimetype=application/octet-stream' },
[0]         { test: /.eot(\?v=\d+.\d+.\d+)?$/, loader: 'file' },
[0]         { test: /.svg(\?v=\d+.\d+.\d+)?$/,
[0]           loader: 'url?limit=10000&mimetype=image/svg+xml' },
[0]         { test: /.css$/, loader: 'style!css' },
[0]         { test: /.less$/,
[0]           loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]_**[hash:base64:5]!autoprefixer?browsers=last 2 version!less?outputStyle=expanded&sourceMap' },
[0]         { test: /.scss$/,
[0]           loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]**_[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap' },
[0]         { test: /.(jpeg|jpg|png|gif)$/,
[0]           loader: 'url-loader?limit=10240' } ] },
[0]   resolve:
[0]    { modulesDirectories: [ 'src', 'node_modules' ],
[0]      extensions: [ '', '.json', '.js', '.jsx', '.scss' ],
[0]      root: '/Users/davidhandel/Desktop/universal-redux-jwt-master/src',
[0]      alias:
[0]       { routes: '/Users/davidhandel/Desktop/universal-redux-jwt-master/src/routes.js',
[0]         middleware: '/Users/davidhandel/Desktop/universal-redux-jwt-master/src/redux/middleware/index.js',
[0]         rootComponent: '/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/lib/helpers/rootComponent.js' } },
[0]   resolveLoader: { modulesDirectories: [ 'src', 'node_modules' ] },
[0]   devtool: 'inline-eval-cheap-source-map',
[0]   plugins:
[0]    [ HotModuleReplacementPlugin {},
[0]      IgnorePlugin {
[0]        resourceRegExp: /webpack-assets.json$/,
[0]        contextRegExp: undefined },
[0]      DefinePlugin { definitions: { __CLIENT**: true, **SERVER**: false } },
[0]      Plugin {
[0]        options:
[0]         { assets:
[0]            { images:
[0]               { extensions: [ 'jpeg', 'jpg', 'png', 'gif' ],
[0]                 parser: [Function] },
[0]              fonts:
[0]               { extensions: [ 'woff', 'woff2', 'ttf', 'eot' ],
[0]                 parser: [Function] },
[0]              svg: { parser: [Function], extensions: [ 'svg' ] },
[0]              style_modules:
[0]               { extensions: [ 'css', 'less', 'scss' ],
[0]                 filter: [Function],
[0]                 path: [Function],
[0]                 parser: [Function] } },
[0]           webpack_assets_file_path: 'node_modules/universal-redux/webpack-assets.json',
[0]           webpack_stats_file_path: 'webpack-stats.json',
[0]           development: true },
[0]        log:
[0]         Log {
[0]           options: { debug: undefined },
[0]           preamble: '[webpack-isomorphic-tools/plugin]' },
[0]        regular_expressions:
[0]         { images: /.(jpeg|jpg|png|gif)$/,
[0]           fonts: /.(woff|woff2|ttf|eot)$/,
[0]           svg: /.svg$/,
[0]           style_modules: /.(css|less|scss)$/ },
[0]        regularExpressions:
[0]         { images: /.(jpeg|jpg|png|gif)$/,
[0]           fonts: /.(woff|woff2|ttf|eot)$/,
[0]           svg: /.svg$/,
[0]           style_modules: /.(css|less|scss)$/ } },
[0]      WebpackErrorNotificationPlugin {
[0]        lastBuildSucceeded: false,
[0]        notifier: [Function],
[0]        opts: { notifyWarnings: true } },
[0]      DefinePlugin {
[0]        definitions:
[0]         { **LOGGER**: 'true',
[0]           **DEVTOOLS**: 'true',
[0]           **DEVELOPMENT**: true,
[0]           **DEVTOOLS_IS_VISIBLE**: 'true',
[0]           **API_ENDPOINT**: '"/api"' } } ] }
[0]
[0] Isomorphic tools config:
[0] { assets:
[0]    { images:
[0]       { extensions: [ 'jpeg', 'jpg', 'png', 'gif' ],
[0]         parser: [Function] },
[0]      fonts:
[0]       { extensions: [ 'woff', 'woff2', 'ttf', 'eot' ],
[0]         parser: [Function] },
[0]      svg: { extension: 'svg', parser: [Function] },
[0]      style_modules:
[0]       { extensions: [ 'css', 'less', 'scss' ],
[0]         filter: [Function],
[0]         path: [Function],
[0]         parser: [Function] } },
[0]   webpack_assets_file_path: 'node_modules/universal-redux/webpack-assets.json' }
[0] ==> 🚧  Webpack development server listening on port 3001
[3] universal-redux configuration is valid.
[3] [ 'JWT Config options:',
[3]   { api: { endpoint: '/v1', host: 'http://localhost', port: 3000 },
[3]     auth:
[3]      { clientId: undefined,
[3]        clientSecret: undefined,
[3]        endpoint: 'undefined/authenticate' },
[3]     debug: true,
[3]     endpoint: '/api',
[3]     sessionStore:
[3]      { type: 'redis',
[3]        prefix: 'jwt-example',
[3]        secret: undefined,
[3]        url: undefined } } ]
[3] [ 'Using Redis for session store' ]
[3] Fri, 29 Jan 2016 18:34:49 GMT express-session deprecated req.secret; provide secret option at node_modules/express-jwt-proxy/lib/index.js:257:42
[3] universal-redux configuration is valid.
[3] universal-redux configuration is valid.
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/ripple/style.scss
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/button/style.scss
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/input/style.scss
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/overlay/style.scss
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/snackbar/style.scss
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/card/style.scss
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/avatar/style.scss
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/commons.scss
[3] [webpack-isomorphic-tools] [error] "/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/webpack-assets.json" not found. Most likely it hasn't yet been generated by Webpack. Using an empty stub instead.
[3] [webpack-isomorphic-tools] [error] asset not found: ./~/flexboxgrid/dist/flexboxgrid.css
[3] universal-redux configuration is valid.
[3] events.js:142
[3]       throw er; // Unhandled 'error' event
[3]       ^
[3]
[3] Error: listen EADDRINUSE :::3000
[3]     at Object.exports._errnoException (util.js:856:11)
[3]     at exports._exceptionWithHostPort (util.js:879:20)
[3]     at Server._listen2 (net.js:1238:14)
[3]     at listen (net.js:1274:10)
[3]     at Server.listen (net.js:1370:5)
[3]     at EventEmitter.listen (/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/express/lib/application.js:617:24)
[3]     at exports.default (/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/universal-redux/lib/start.js:16:10)
[3]     at Object.<anonymous> (start_es6.js:13:1)
[3]     at Module._compile (module.js:399:26)
[3]     at loader (/Users/davidhandel/Desktop/universal-redux-jwt-master/node_modules/babel-register/lib/node.js:130:5)
[3]
[3] npm
[3]
[3] ERR!
[3]  Darwin 15.3.0
[3] npm
[3]  ERR! argv "/Users/davidhandel/.nvm/versions/node/v5.2.0/bin/node" "/Users/davidhandel/.nvm/versions/node/v5.2.0/bin/npm" "run" "dev-server"
[3] npm
[3]  ERR! node v5.2.0
[3] npm
[3]  ERR! npm  v3.3.12
[3] npm
[3]  ERR! code ELIFECYCLE
[3] npm ERR!
[3]  universal-redux-jwt@0.0.1 dev-server: `better-npm-run dev-server`
[3] npm ERR! Exit status 1
[3] npm ERR!
[3]
[3] npm ERR! Failed at the universal-redux-jwt@0.0.1 dev-server script 'better-npm-run dev-server'.
[3] npm ERR!
[3]  Make sure you have the latest version of node.js and npm installed.
[3] npm ERR! If you do, this is most likely a problem with the universal-redux-jwt package,
[3] npm ERR! not with npm itself.
[3] npm ERR! Tell the author that this fails on your system:
[3] npm ERR!     better-npm-run dev-server
[3] npm ERR!
[3]  You can get their info via:
[3] npm ERR!     npm owner ls universal-redux-jwt
[3] npm ERR!
[3]  There is likely additional logging output above.
[3]
[3] npm ERR! Please include the following file with any support request:
[3] npm ERR!     /Users/davidhandel/Desktop/universal-redux-jwt-master/npm-debug.log
[3] npm run dev-server exited with code 1
--> Sending SIGTERM to other processes..
[0] Hash: dc688423d26837fea81d
[0] Version: webpack 1.12.12
[0] Time: 3622ms
[0]                        Asset     Size  Chunks             Chunk Names
[0] main-dc688423d26837fea81d.js  6.58 MB       0  [emitted]  main
[0] webpack built dc688423d26837fea81d in 3622ms

**Comment by bdefore** [comment] 2016-01-29 19:44
looks like it's having trouble starting on port 3000. might you have another express server running somewhere?

**Comment by dbhandel** [comment] 2016-01-29 19:56
I thought that might be the issue but when I do a lsof -i:3000 nothing is shown. Also on a reboot of my Mac, the first attempt at npm run dev shows the same error messages.

**Comment by catamphetamine** [comment] 2016-01-29 19:57
"Authentication server running at undefined:undefined"
why is that?

**Comment by bdefore** [comment] 2016-01-29 19:57
have you made any modifications? I'll have a look to try to repro in a few
hours

**Comment by dbhandel** [comment] 2016-01-29 20:01
No modifications whatsoever. Thanks @bdefore .

**Comment by sexyoung** [comment] 2016-02-02 17:09
I git clone it and `npm install` & `npm run dev`
it just say `Error: listen EADDRINUSE :::3000` ...
I have no another one service running port 3000
why?

**Comment by bdefore** [comment] 2016-02-02 17:14
Could this be an issue with the `PORT` variable not being picked up from `better-npm-run` in package.json. Perhaps you're running on Windows? This example runs with three servers that should be running on ports 3000, 3030, and 3060. My output mentions the auth server: `Authentication server running at http://localhost:3060` whereas @dbhandel I see you're getting `Authentication server running at undefined:undefined`

**Comment by bartolkaruza** [comment] 2016-02-10 11:24
@bdefore I'm having this same port issue on mac (testing the koa PR in UR). Did you find out what the issue is?

**Comment by bartolkaruza** [comment] 2016-02-10 11:29
```
cp .env.example .env
```

Issue was caused for me by skipping that step. Server ports are configured correctly after executing that env setup

**Comment by bdefore** [comment] 2016-02-10 16:51
Thanks for identifying that @bartolkaruza !

**Comment by bdefore** [comment] 2016-02-16 00:57
Closing for now as I believe the `.env` step was the cause. Please re-open if verification finds that's not true.

**Closed as completed by bdefore** 2016-02-16 00:57 UTC
